/****** Script for SelectTopNRows command from SSMS  ******/
SELECT   [CustomerKey]
      ,c.[GeographyKey],g.City,g.[EnglishCountryRegionName] as [Country]
     -- ,[CustomerAlternateKey]
      ,[Title]
      ,concat([FirstName],[LastName]) as [full name]
     -- ,[MiddleName]
     -- ,[LastName]
      --,[NameStyle]
      ,[BirthDate]
     -- ,[MaritalStatus]
    --  ,[Suffix]
      ,case when [Gender]='m' then 'Male'when [Gender]='f' then 'Female' end as [Gender]
      ,[EmailAddress]
      --,[YearlyIncome]
     -- ,[TotalChildren]
     -- ,[NumberChildrenAtHome]
     -- ,[EnglishEducation]
     -- ,[SpanishEducation]
     -- ,[FrenchEducation]
    --  ,[EnglishOccupation]
     -- ,[SpanishOccupation]
     -- ,[FrenchOccupation]
     -- ,[HouseOwnerFlag]
     -- ,[NumberCarsOwned]
    --  ,[AddressLine1]
     -- ,[AddressLine2]
     -- ,[Phone]
      ,[DateFirstPurchase]
     -- ,[CommuteDistance]
  FROM [AdventureWorksDW2019].[dbo].[DimCustomer] c left join [dbo].[DimGeography] g
  on c.GeographyKey=g.GeographyKey
  order by [CustomerKey]